version: "3.9"

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
